### ISSUE TITLE
TypeError: coercing to str: need a bytes-like object, NoneType found

### ISSUE THREAD

**Issue by sperlic** [GOVCERT-LU/eml_parser#20] opened 2018-05-18 17:37 UTC
Hello, 

Need help parsing a particular EML file that can not be attached here due to confidentiality. If EML is still needed after this information, I can send it via email or in some other way.

**OS:** Debian 9.2
**Python:** 3.5.3
**eml_parser:** 1.8
**file-magic:** 0.3.0
**EML generated by:** `User-agent: Microsoft-MacOutlook/10.c.0.180410`
**Has attachments:** Yes

**test.py** _(code from readme)_
```python
import eml_parser


def json_serial(obj):
    if isinstance(obj, datetime.datetime):
        serial = obj.isoformat()
        return serial


with open('sample.eml', 'rb') as fhdl:
    raw_email = fhdl.read()

parsed_eml = eml_parser.eml_parser.decode_email_b(raw_email)

print(json.dumps(parsed_eml, default=json_serial))
```
Running  `python3.5 test.py` returns an error
```python
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    parsed_eml = eml_parser.eml_parser.decode_email_b(raw_email)
  File "/usr/local/lib/python3.5/dist-packages/eml_parser/eml_parser.py", line 317, in decode_email_b
    return parse_email(msg, include_raw_body, include_attachment_data, pconf)
  File "/usr/local/lib/python3.5/dist-packages/eml_parser/eml_parser.py", line 774, in parse_email
    report_struc['attachment'] = traverse_multipart(msg, 0, include_attachment_data)
  File "/usr/local/lib/python3.5/dist-packages/eml_parser/eml_parser.py", line 196, in traverse_multipart
    attachments.update(traverse_multipart(part, counter, include_attachment_data))  # type: ignore
  File "/usr/local/lib/python3.5/dist-packages/eml_parser/eml_parser.py", line 234, in traverse_multipart
    attachments[file_id]['mime_type'] = magic_none.buffer(data)
  File "/usr/local/lib/python3.5/dist-packages/magic.py", line 152, in buffer
    return str(r, 'utf-8')
TypeError: coercing to str: need a bytes-like object, NoneType found
```
Do you have an idea without reviewing the EML file?

Thank you!

**Comment by sim0nx** [comment] 2018-06-01 12:35
Hi,

I do have an idea what the problem is. That is the magic library fails to determine a valid mime type and thus its private method returns None.
IMHO there is a bug in the file-magic library as it clearly states that the buffer() method would return None as well in that case, though it does not.
It tries to convert the return value to a string "return str(r, 'utf-8')", which is not valid for None.

... which is the error you are seeing.

I will see what I can do in that case.

**Comment by sim0nx** [comment] 2018-06-01 12:36
Can you tell me what type of attachement that is you are having that issue with ?

**Comment by sim0nx** [comment] 2018-06-01 13:29
I have released a new version which should provide a workaround for the mentioned file-magic issue.
Please test it and let me know if this fixes your issue or not.

**Comment by sim0nx** [comment] 2018-06-01 21:13
file-magic module was update on pypi (0.4.0) which includes a fix. I have thus removed the workaround in eml-parser.

I am closing this issue as I believe it is fixed now. In case it isn't, please do let me know.

**Closed by sim0nx** 2018-06-01 21:13 UTC

**Comment by sperlic** [comment] 2018-06-09 07:12
Hi, thanks a lot on the answers. I will try out the offered solutions and let me know if we succeed, although I expect it to be resolved.

All the best!

**Comment by sperlic** [comment] 2018-06-10 01:44
I just upgraded the file-magic package on the production server and the problem is solved.
Thanks again.

P.S. Sorry for the late reply, I missed this github notification last week :pensive:

**Comment by sim0nx** [comment] 2018-06-11 17:29
Great! Glad that did the trick! :-)
